### ISSUE TITLE
Give an option to add a red asterisks to the label of the required fields

### ISSUE THREAD

**Issue by toshiya14** [vue-generators/vue-form-generator-docs#31]
For accessibility requirements, the required fields should add a red asterisk.

```html
<label for="firstname">First name <abbr class="req" title="required">*</abbr>:</label>
```
I'd like to know if there is any option could help it.
If not, I'd like to request this feature.

As the articles below explained.
https://www.w3.org/TR/WCAG20-TECHS/H90.html#H90-ex2
https://vue-generators.gitbook.io/vue-generators/validation

Thanks.

**Comment by toshiya14** [comment]
For now, I am using the follow codes to implements this.

```scss
    .form-group {
      // ...
      &.required {
        & > label::after {
          content: "*";
          color: red;
        }
      }
```
